 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic.h
 *
 * Description: Header file for the AVR Ultrasonic driver
 *
 * Author: Jana Wael
 *
 *******************************************************************************/



#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TRIGGER_PORT PORTB_ID
#define TRIGGER_PIN PIN5_ID


/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/


/* Function Name : Ultrasonic_init
 * Description : Function responsible for Initialize the ICU driver as required.
 *				 Setup the ICU call back function.
				 Setup the direction for the trigger pin as output pin through the
				 GPIO driver.
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_init(void);

/* Function Name : Ultrasonic_Trigger
 * Description :This function Sends the Trigger pulse to the ultrasonic.
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_Trigger(void);

/* Function Name : Ultrasonic_readDistance
 * Description : Function responsible for Sending the trigger pulse by using Ultrasonic_Trigger function.
                 Start the measurements by the ICU from this moment.
 * Parameters : void.
 * Return : uint16: Ultrasonic value
 */
uint16 Ultrasonic_readDistance(void);

/* Function Name : Ultrasonic_edgeProcessing
 * Description :This is the call back function called by the ICU driver.
 				This is used to calculate the high time (pulse time) generated by
				the ultrasonic sensor
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
