 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: Ultrasonic.c
 *
 * Description: Source file for the AVR Ultrasonic driver
 *
 * Author: Jana Wael
 *
 *******************************************************************************/

#include "ultraSonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

static uint8 g_edgeCount = 0;
static uint16 g_timeHigh = 0;
static uint16 distance = 0;


/* Function Name : Ultrasonic_init
 * Description : Function responsible for Initialize the ICU driver as required.
 *				 Setup the ICU call back function.
				 Setup the direction for the trigger pin as output pin through the
				 GPIO driver.
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_init(void){

	/*
	* Create configuration structure for ICU driver
	*/
	ICU_ConfigType ICU_Configs = {F_CPU_8, RAISING};

	/*
	* Set the Call back function pointer in the ICU driver
	*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/*
	* Initialize ICU driver
	*/
	ICU_init(&ICU_Configs);

	/*
	*  Configure the Trigger pin as output pin
	*/
	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, PIN_OUTPUT);

}


/* Function Name : Ultrasonic_Trigger
 * Description :This function Sends the Trigger pulse to the ultrasonic.
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_Trigger(void){

	/*
	* Send the Trigger pulse to the ultrasonic.
	*/
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_HIGH);

	_delay_us(10);

	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

}


/* Function Name : Ultrasonic_readDistance
 * Description : Function responsible for Sending the trigger pulse by using Ultrasonic_Trigger function.
                 Start the measurements by the ICU from this moment.
 * Parameters : void.
 * Return : uint16: Ultrasonic value
 */
uint16 Ultrasonic_readDistance(void){

	/*
	* Send the trigger pulse by using Ultrasonic_Trigger function
	*/
	Ultrasonic_Trigger();

	/*
	* Wait until the echo is received
	*/
	while(g_edgeCount < 2){

	}
	g_edgeCount = 0;

	distance = ((float32)(g_timeHigh / 58)) + 1;

	return distance;
}


/* Function Name : Ultrasonic_edgeProcessing
 * Description :This is the call back function called by the ICU driver.
 				This is used to calculate the high time (pulse time) generated by
				the ultrasonic sensor
 * Parameters : void.
 * Return : void.
 */
void Ultrasonic_edgeProcessing(void){

	g_edgeCount++;
	if(g_edgeCount == 1){

		/*
		* Clear the timer counter register to start measurements from the
		* first detected rising edge
		*/
		ICU_clearTimerValue();

		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
		else if(g_edgeCount == 2){

			/* Store the High time value */
			g_timeHigh = ICU_getInputCaptureValue();

			/* Detect rising edge */
			ICU_setEdgeDetectionType(RAISING);
		}

	}
